# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ramo828/Belgeler/numb_v2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ramo828/Belgeler/numb_v2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramo828/Belgeler/numb_v2/CMakeFiles /home/ramo828/Belgeler/numb_v2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ramo828/Belgeler/numb_v2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named numb

# Build rule for target.
numb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 numb
.PHONY : numb

# fast build rule for target.
numb/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/build
.PHONY : numb/fast

numb.o: numb.cpp.o
.PHONY : numb.o

# target to build an object file
numb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/numb.cpp.o
.PHONY : numb.cpp.o

numb.i: numb.cpp.i
.PHONY : numb.i

# target to preprocess a source file
numb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/numb.cpp.i
.PHONY : numb.cpp.i

numb.s: numb.cpp.s
.PHONY : numb.s

# target to generate assembly for a file
numb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/numb.cpp.s
.PHONY : numb.cpp.s

sources/mylib.o: sources/mylib.cpp.o
.PHONY : sources/mylib.o

# target to build an object file
sources/mylib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/mylib.cpp.o
.PHONY : sources/mylib.cpp.o

sources/mylib.i: sources/mylib.cpp.i
.PHONY : sources/mylib.i

# target to preprocess a source file
sources/mylib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/mylib.cpp.i
.PHONY : sources/mylib.cpp.i

sources/mylib.s: sources/mylib.cpp.s
.PHONY : sources/mylib.s

# target to generate assembly for a file
sources/mylib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/mylib.cpp.s
.PHONY : sources/mylib.cpp.s

sources/runner.o: sources/runner.cpp.o
.PHONY : sources/runner.o

# target to build an object file
sources/runner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/runner.cpp.o
.PHONY : sources/runner.cpp.o

sources/runner.i: sources/runner.cpp.i
.PHONY : sources/runner.i

# target to preprocess a source file
sources/runner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/runner.cpp.i
.PHONY : sources/runner.cpp.i

sources/runner.s: sources/runner.cpp.s
.PHONY : sources/runner.s

# target to generate assembly for a file
sources/runner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/numb.dir/build.make CMakeFiles/numb.dir/sources/runner.cpp.s
.PHONY : sources/runner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... numb"
	@echo "... numb.o"
	@echo "... numb.i"
	@echo "... numb.s"
	@echo "... sources/mylib.o"
	@echo "... sources/mylib.i"
	@echo "... sources/mylib.s"
	@echo "... sources/runner.o"
	@echo "... sources/runner.i"
	@echo "... sources/runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

